server:
  port: 8090 # 项目启动端口

spring:
  data:
    redis:
      host: localhost # Redis URL 链接
      port: 6379 # Redis 端口
  ai:
    deepseek:
      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
      api-key: sk-111 # 填写 DeepSeek Api Key，改成你自己的
      chat:
        options:
          model: deepseek-reasoner # 使用哪个模型
          temperature: 0.0 # 温度值
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-111  # 填写阿里百炼的 API Key, 改成你自己的
      embedding:
        options:
          model: text-embedding-v4 # 向量模型
    vectorstore:
      redis:
        initialize-schema: true # 是否初始化模式
        index-name: xiaohong-ai-index # 自定义索引名称
        prefix: embedding # 自定义键名前缀
