server:
  port: 8000 # 启动端口号
spring:
  ai:
    mcp:
      server:
        type: sync # 处理模式，SYNC 同步或 ASYNC 异步
        name: mcp-server-qq # MCP Server 名称
        version: 1.0.0 # MCP Server 版本号

# 奶思猫 API 密钥(替换为你自己的)
api-key: 5tJgSdXytm9b1GOxKVk7lMIzJq