server:
  port: 8080 # 项目启动端口

spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-e935d90ace984a9483f1e7045638850a  # 填写智增增的 API Key, 该成你自己的
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # 数据库驱动类名
    url: jdbc:p6spy:postgresql://localhost:5433/robot # 数据库连接 URL
    username: postgres # 数据库用户名
    password: postgres # 数据库密码
    hikari: # HikariCP 连接池配置
      pool-name: AI-Robot-HikariCP # 自定义连接池名称
      auto-commit: true # 是否自动提交事务
      connection-timeout: 30000 # 连接超时时间（毫秒）
      idle-timeout: 600000 # 空闲连接存活最大时间（毫秒）
      max-lifetime: 1800000 # 连接最大存活时间（毫秒）
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 20 # 最大连接池大小
      connection-test-query: SELECT 1 # 连接测试查询
      validation-timeout: 5000 # 验证连接的有效性